### ISSUE TITLE
`desktop-app install` fails on Linux

### ISSUE THREAD

**Issue by demberto** [chrisjbillington/desktop-app#21]
```python
>>> desktop-app install dycall
Traceback (most recent call last):
  File "/home/demberto/.local/bin/desktop-app", line 8, in <module>
    sys.exit(main())
  File "/home/demberto/.local/lib/python3.8/site-packages/desktop_app/__main__.py", line 50, in main
    install(module, path=args.path, verbose=not args.quiet,
  File "/home/demberto/.local/lib/python3.8/site-packages/desktop_app/shell.py", line 264, in install
    create_desktop_file(
  File "/home/demberto/.local/lib/python3.8/site-packages/desktop_app/linux.py", line 41, in create_desktop_file
    path.write_text(dedent(contents), encoding='utf8')
  File "/usr/lib/python3.8/pathlib.py", line 1255, in write_text
    with self.open(mode='w', encoding=encoding, errors=errors) as f:
  File "/usr/lib/python3.8/pathlib.py", line 1222, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/usr/lib/python3.8/pathlib.py", line 1078, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/demberto/.local/share/applications/dycall.desktop'
```

**Comment by chrisjbillington** [comment]
Thanks for the bug report. Looks like `/home/demberto/.local/share/applications/` doesn't exist. Is that correct?

If so, the fix should be easy enough, will just need to make the calling code create the directory.

**Comment by demberto** [comment]
Damn, I will check this tommorow for sure. Yea the fix would be simple, like using `os.mkdirs`.
