### ISSUE TITLE
Errors with conda environment

### ISSUE THREAD

**Issue by rpanderson** [chrisjbillington/desktop-app#4]
Trying this on an Anaconda environment:
```
(base) C:\Users\rpanderson>desktop-app install oink
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\Scripts\desktop-app-script.py", line 11, in <module>
    load_entry_point('desktop-app', 'console_scripts', 'desktop-app')()
  File "c:\programdata\anaconda3\lib\site-packages\pkg_resources\__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\programdata\anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2862, in load_entry_point
    return ep.load()
  File "c:\programdata\anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2453, in load
    return self.resolve()
  File "c:\programdata\anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2459, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\users\rpanderson\src\desktop-app\desktop_app\__init__.py", line 18, in <module>
    from .launcher import entry_point
  File "c:\users\rpanderson\src\desktop-app\desktop_app\launcher.py", line 6, in <module>
    from .environment import (
  File "c:\users\rpanderson\src\desktop-app\desktop_app\environment.py", line 28, in <module>
    @lru_cache
  File "c:\programdata\anaconda3\lib\functools.py", line 490, in lru_cache
    raise TypeError('Expected maxsize to be an integer or None')
TypeError: Expected maxsize to be an integer or None
```
Debugger indicates `maxsize` is:
```python
ipdb> type(maxsize)
<class 'function'>
ipdb> maxsize.__name__
'detect_conda_env'
```

Tested with conda 4.8.1 and 4.8.3 (both Python 3.7).

**Comment by chrisjbillington** [comment]
Thanks! Looks like the ability to use the lru_cache decorator directly on a function, without giving it a maxsize argument, was added in 3.8.
